name: Deploy Website 

on: 
  push: 
    branches: 
      - main
      

permissions: 
  contents: read 
  pages: write 
  id-token: write 

jobs: 
  projectdeploy: 
    runs-on: ubuntu-latest 
    environment: 
      name: github-pages 

    steps: 
      - name: Checkout Repository 
        uses: actions/checkout@v4 

      - name: Display Deployment Message
        run: echo "Now being Deployed Using GitHub Actions"

      - name: Setup Pages
        uses: actions/configure-pages@v4 

      - name: Upload Artifact 
        uses: actions/upload-pages-artifact@v3
        with:  
          path: .  

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
